### PR TITLE
include `canonical_ref` of blockchain objects in index

### PR DESCRIPTION
**Pull request by yusefnapora**
Depends on https://github.com/mediachain/mediachain-client/pull/82

gets the canonical ref from the updated `canonical_stream` method, and inserts it into the index at the `canonical_ref` key (sibling to `latest_ref`)

### CODE REVIEW

**Comment by yusefnapora** [comment]
we should set the mediachain-client dependency to 0.1.7 and probably bump the indexer version

**Comment by parkan** [comment]
Ok push to this branch again and we'll re-merge

**Comment by yusefnapora** [comment]
I just pushed the dependency bump to master a second ago 😬  It looks like tim set the indexer version to 0.0.14 a few commits back, and we've only published 0.0.12 so far, so we could probably leave the indexer version alone and just publish it as is

**Comment by parkan** [comment]
Yeah we should get our versioning somewhat more in sync

**Comment by autoencoder** [comment]
Syncing version numbers - So each time the Indexer changes its REST API and needs a version bump, we should bump the version number of the Client too? Sure, we can do it that way if you guys want :)

**Comment by parkan** [comment]
Well, I mean at least minor version numbers that are vaguely similar (0.1.x series?)

Small detail but keeps things a bit more consistent

**Pull request merged**
